# Generated by Django 6.1 on 2026-09-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
